### ISSUE TITLE
DNC Can not add widget

### ISSUE THREAD

**Issue by kschost100** [MrCMS/MrCMS#94]
Hello, Very nice project you have here, I have tried the DNC version and seams to build well, i did however run into issue with blank screen after install, But had seen an issue with it and when i set pages to published everything loaded nice.

Anyway i tried to add a text widget to a page and i get the first popup asking for name and type, i select this page and text widget and give name then hit save and it does nothing, I do see a log created in the admin the shows the following.

Value cannot be null. Parameter name: type    at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at MrCMS.Web.Apps.Admin.Services.WidgetAdminService.AddWidget(AddWidgetModel model, Object additionalPropertyModel) in C:\Projects\MrCMS\src\Lib\MrCMS.Web.Apps.Admin\Services\WidgetAdminService.cs:line 42
   at MrCMS.Web.Apps.Admin.Controllers.WidgetController.Add_POST(AddWidgetModel model) in C:\Projects\MrCMS\src\Lib\MrCMS.Web.Apps.Admin\Controllers\WidgetController.cs:line 47
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at MrCMS.Website.CurrentWebpageMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\Projects\MrCMS\src\Lib\MrCMS\Website\CurrentWebpageMiddleware.cs:line 27
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at MrCMS.Website.CurrentSiteSettingsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\Projects\MrCMS\src\Lib\MrCMS\Website\CurrentSiteSettingsMiddleware.cs:line 20
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at MrCMS.Logging.MrCMSLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\Projects\MrCMS\src\Lib\MrCMS\Logging\MrCMSLoggingMiddleware.cs:line 20.

My Experiance is more of a GUI guy but can kind of try and figure things out, But I can not seem to find this issue. 

Any help would be a great help.

Thanks

**Comment by kschost100** [comment]
I apologize, I had used the wrong Branch, i had used articles branch, which i see is not up to date with Core. It is working now.
